### ISSUE TITLE
Hardware recommendation

### ISSUE THREAD

**Issue by sponz** [mtdcr/comfoair-mqtt-bridge#1]
Hi,

Thanks for your nice work!

Question, what is your hardware recommendation? Are you using a RPi? ¨

How do you connect to the CC Ease? Do you use a USB-serial adapter? 

Regards!

**Comment by mtdcr** [comment]
Hi @sponz! I connected a USB-serial adapter to the RS232-PC port of the Comfoair system board, I think using an additional null modem cable. There are no special requirements. I use an Odroid XU4, but you can probably use anthing capable of running Linux to connect to a local or remote (ser2net-compatible) serial port.
