### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Jemp4567** [mtdcr/comfoair-mqtt-bridge#5]
Hello, 
I'm trying to get the values of my zehnder comfoair 180 unit. What I have found on the internet is that the unit is using RS232 and so I think that it should work with this script. 
The script is running and I can see on my mqtt broker that the topic "ComfoAir/raspberrypi:ttyUSB0/availability" is created and the value is offline.
Running the script with 
`sudo python3.9 comfoair-mqtt-bridge.py --broker mqtt://192.168.178.123 --port /dev/ttyUSB0 --debug
`
I can see the following lines:
`Sending CONNECT (u0, p0, wr1, wq2, wf1, c1, k60) client_id=b''
Received CONNACK (0, 0)
Watchdog: Starting
Watchdog: Waiting for data
unfiltered_messages() is deprecated and will be removed in a future version. Use messages() instead.
Sending SUBSCRIBE (d0, m1) [(b'ComfoAir/raspberrypi:ttyUSB0/command', 0)]
Received SUBACK
Sending SUBSCRIBE (d0, m2) [(b'ComfoAir/raspberrypi:ttyUSB0/preset_mode_command', 0)]
Received SUBACK
Sending SUBSCRIBE (d0, m3) [(b'ComfoAir/raspberrypi:ttyUSB0/keys_short', 0)]
Received SUBACK
Sending SUBSCRIBE (d0, m4) [(b'ComfoAir/raspberrypi:ttyUSB0/keys_long', 0)]
Received SUBACK
Running mainloop
Watchdog: Timeout, trying to recover
Publish: ComfoAir/raspberrypi:ttyUSB0/availability b'offline'
Sending PUBLISH (d0, q2, r1, m5), 'b'ComfoAir/raspberrypi:ttyUSB0/availability'', ... (7 bytes)
Received PUBREC (Mid: 5)
Sending PUBREL (Mid: 5)
Received PUBCOMP (Mid: 5)
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Sending PINGREQ
Received PINGRESP
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
Watchdog: Timeout, trying to recover
Watchdog: Waiting for data
`

With the command `ls -la /dev/serial/by-id/` I can see that the USB port is
`usb-FTDI_FT232R_USB_UART_AC00V4R6-if00-port0 -> ../../ttyUSB0`

The usb serial adapte is attached on the cable of the comfosense unit (without the unit). the 2(tx) Wire is attached on the connection RXD Pin of my serial adapter and 1(RX) on TXD Pin. GND on GND .

What do I have to change / to test?

**Comment by mtdcr** [comment]
> The usb serial adapte is attached on the cable of the comfosense unit (without the unit).

The program tries to passively coexist with the EASE unit, which polls the values from the central unit. I guess the ComfoSense is a drop-in replacement, so it may work as well. Can you reconnect it and use the serial port labeled RS232-PC or similar instead?

If you don't want to or can't connect the ComfoSense, you'll have to implement the polling yourself.

The code contains at least one active command to simulate a key press. You could take it as an example and look for reverse engineered protocol docs on the net.
